### ISSUE TITLE
Weird display when used with Isabelle2017

### ISSUE THREAD

**Issue by vbeffara** [siegebell/vsc-prettify-symbols-mode#30] opened 2017-11-27 21:10 UTC
On a mac, with up-to-date VSCode insiders and plugins, code replaced by symbols in Isabelle/HOL files appears huge, like shown in the attached picture. This looks a bit like issue #28 actually, except that folding is not necessary to reproduce it.
<img width="564" alt="screen shot 2017-11-27 at 20 04 37" src="https://user-images.githubusercontent.com/248972/33289392-b11d9a38-d3bf-11e7-9d39-a2fa7da63adc.png">

**Comment by chiragbharadwaj** [comment] 2017-12-18 02:16
I have the same issue when using Coq 8.7 in VSCode. Also with a Mac.

**Comment by fmorgner** [comment] 2017-12-20 12:27
I have the same issue, in my case with Haskell code, running on Arch Linux.

**Comment by dan323** [comment] 2017-12-27 20:07
I changed in decorations.js the font-size from 10em to 1em in two places and it works for me now. Until it is fixed in the sources, you can change it by yourself in your computer.

**Comment by vbeffara** [comment] 2017-12-28 18:26
That fix works for me, thanks!

**Comment by chiragbharadwaj** [comment] 2017-12-29 19:00
@dan323 Which two places? I only see "10em" in one place, namely on Line 29 in the TypeScript source. What was the second place you changed it in?

Thanks for the suggestion, btw.

**Comment by siegebell** [comment] 2018-03-24 19:48
This is caused by a change in behavior of before/after decorations in vscode.

**Comment by siegebell** [comment] 2018-03-24 19:52
Caused by #34.

**Closed as completed by siegebell** 2018-03-24 19:52 UTC
Labels: bug

**Comment by siegebell** [comment] 2018-03-24 20:35
Fixed in release 0.4.1
